### ISSUE TITLE
srcPath does not always work correctly

### ISSUE THREAD

**Issue by FallSe7en** [dataworker/dataworker#17]
The anonymous function that determines srcPath is subject to race conditions and does not always return the correct value.

**Comment by redbmk** [comment]
I think a little more work could be done to figure out if it's safe to attempt to use `srcPath` as a last resort. Right now it just assumes it's OK to try, but really it could be `require.js` or the most recent asynchronously accessed file. It should be possible to detect those cases and then ignore the `srcPath` option. Another idea would be to require `backupWorkerSource` to be provided and remove the `srcPath` thing altogether. That would probably require moving to v3.0, since it would make it so IE can no longer access remote datasources inside web workers without extra configuration.

**Comment by redbmk** [comment]
Plan on adding [this polyfill](https://github.com/JamesMGreene/document.currentScript) for detecting the current source path. document.currentScript works in non-IE modern browsers.
